### ISSUE TITLE
Use save_pretrained to make the model locally available

### ISSUE THREAD

**Issue by tkilias** [exasol/transformers-extension#125]
# Background:

- Currently, we use from_pretrained with the cache_dir option to load the model and upload the cache directory to the BucketFS
- The current approach in general works, but seems to check each time online if the model exists, or we have access and if we have the newest version
- This is not possible in some deployments 
- To solve this issue, we could follow the following [example](https://huggingface.co/docs/transformers/v4.32.1/en/installation#fetch-models-and-tokenizers-to-use-offline) using save_pretrained which stores the model into a directory which we then could upload
- We can then load the model with from_pretrained from a local path

# Acceptance Criteria

- Change download of model to save_pretrained
- Upload the save model to the BucketFS
- Use a local path to load the model during inference

**Comment by MarleneKress79789** [comment]
suggested splitting of this ticket:

- familiarize self with huggingface api
- add new functionality 
- -  download
- - upload
- - load
- add tests for new functionality
- -  download
- - upload
- - load
- change code to use new functionality ,remove check for newest version (should this be toogleable?)
- -  download
- - upload
- - load

**Comment by MarleneKress79789** [comment]
new tickets are

- #143
- #144
- #145
- #146
- #147
