### ISSUE TITLE
Support for Transformer Embeddings

### ISSUE THREAD

**Issue by exa-eswar** [exasol/transformers-extension#131]
Support for https://pypi.org/project/transformer-embeddings/

**Comment by exa-eswar** [comment]
@tkilias @redcatbear FYI

**Comment by exa-eswar** [comment]
example: https://huggingface.co/tasks/feature-extraction

**Comment by exa-eswar** [comment]
https://huggingface.co/sentence-transformers

**Comment by tkilias** [comment]
Shelved for the moment, can be reopened if we decide to put it on the roadmap
