### ISSUE TITLE
Add load class which loads model from local path

### ISSUE THREAD

**Issue by MarleneKress79789** [exasol/transformers-extension#145]
# Background:

- Currently, we use from_pretrained with the cache_dir option to load the model and upload the cache directory to the BucketFS
- The current approach in general works, but seems to check each time online if the model exists, or we have access and if we have the newest version
- This is not possible in some deployments 
- To solve this issue, we could follow the following [example](https://huggingface.co/docs/transformers/v4.32.1/en/installation#fetch-models-and-tokenizers-to-use-offline) using save_pretrained which stores the model into a directory which we then could upload
- We can then load the model with from_pretrained from a local path
- After we extracted the load class in #144 , we can then create a new load function which loads the model from a local path during inference

```[tasklist]
### Acceptance Criteria
- [x] Create a load class, which uses a local path to load the model during inference
- [x] add tests for new load function
- [x] add documentaion for the new load function like doc strings, full user docu will be added in #146
```

**Comment by ckunki** [comment]
Did some review, see comments in Confluence. 
Effort: 0.1
