### ISSUE TITLE
Solve version conflict with torch 2.1.0+cpu and python 3.11

### ISSUE THREAD

**Issue by MarleneKress79789** [exasol/transformers-extension#165]

**Comment by ahsimb** [comment]
The conflict is not with the version of Python. There is no CPU version of pytorch in pypi. This is reflected in the [User Guide](https://github.com/exasol/transformers-extension/blob/main/doc/user_guide/user_guide.md#:~:text=pip%20install%20%3Cpath/wheel%2Dfilename.whl%3E%20%2D%2Dextra%2Dindex%2Durl%20https%3A//download.pytorch.org/whl/cpu)

**Comment by MarleneKress79789** [comment]
we dont download the torch+cpu package from pypi. it should be downloaded from https://download.pytorch.org/whl/cpu

**Comment by tkilias** [comment]
I think, this issue solved, because we changed the dependency to the normal pypi version and only use a different version in the SLC.
