### ISSUE TITLE
IndexError: tuple index out of range for model downloader

### ISSUE THREAD

**Issue by exa-eswar** [exasol/transformers-extension#187]
SELECT TRANSFORMERS.TE_MODEL_DOWNLOADER_UDF(
    'd4data/bias-detection-model',
    'translate',
    'TRANSFORMERS_BUCKET',
    ''
)

```
Code: 0, SQL State: 22002]  VM error: F-UDF-CL-LIB-1127: F-UDF-CL-SL-PYTHON-1002: F-UDF-CL-SL-PYTHON-1026: ExaUDFError: F-UDF-CL-SL-PYTHON-1114: Exception during run 
TE_MODEL_DOWNLOADER_UDF:8 run
  File "/usr/local/lib/python3.8/dist-packages/exasol_transformers_extension/udfs/models/model_downloader_udf.py", line 27, in run
    model_path = self._download_model(ctx)
  File "/usr/local/lib/python3.8/dist-packages/exasol_transformers_extension/udfs/models/model_downloader_udf.py", line 52, in _download_model
    bucketfs_location = self._bucketfs_factory.create_bucketfs_location(
  File "/usr/local/lib/python3.8/dist-packages/exasol_bucketfs_utils_python/bucketfs_factory.py", line 46, in create_bucketfs_location
    url_path.parts[2]).joinpath(*url_path.parts[3:])
IndexError: tuple index out of range
(Session: 1790709593734184960)
```

**Comment by tkilias** [comment]
The bucketfs connection currently expects a path in bucket. This relates to the following issue:
https://github.com/exasol/bucketfs-python/issues/77

**Comment by tkilias** [comment]
also related to https://github.com/exasol/transformers-extension/issues/188

**Comment by tkilias** [comment]
This bug will be obsolete as soon, we replace the BucketFSLocation with the PathLike Interface and PathBuilder in newer versions of BucketFS-Python. This should happen in Q3.

**Comment by tkilias** [comment]
solved with https://github.com/exasol/transformers-extension/pull/240, because new BucketFS Python PathLike api uses json config in the connection instead of urls
