### ISSUE TITLE
Export db connection fixtures to a new pytest plugin

### ISSUE THREAD

**Issue by ahsimb** [exasol/transformers-extension#250]
The fixtures to go are:
- `backend`.
- `pyexasol_connection` (`db_conn` in the Sagemaker Extension) with its entourage - `pyexasol_connection_onprem` `pyexasol_connection_saas` and all the fixtures it depends on.
- `bucketfs_location` with its entourage - `bucketfs_location_onprem`, `bucketfs_location_saas` and all the fixtures it depends on.
- `deploy_params` (a more consistent name would be `pyexasol_connection_params` or `db_conn_params`) and `upload_params` (a more consistent name would be `bucketfs_location_params`)

**Comment by tkilias** [comment]
obsolete
