### ISSUE TITLE
Address "insufficient privileges for creating schema"

### ISSUE THREAD

**Issue by exa-eswar** [exasol/transformers-extension#62]

**Comment by tkilias** [comment]
@exa-eswar please describe this issue in more detail. However, my guess is, you are trying to install the extension into a database, where you don't have the permissions to create a schema. Did you try to use an existing schema?

**Comment by exa-eswar** [comment]
@tkilias I am trying to use the existing schema, yet I got the issue mentioned. 
<img width="932" alt="Screenshot 2022-10-05 at 11 28 31" src="https://user-images.githubusercontent.com/97116849/193991607-433381fd-4ec5-445c-b614-fb7a8030abfc.png">


Yes, I am trying to use database where I don't have CREATE SCHEMA permissions.
