### ISSUE TITLE
Connectionpool - optional HTTPS connection

### ISSUE THREAD

**Issue by exa-eswar** [exasol/transformers-extension#63]

**Comment by tkilias** [comment]
@exa-eswar please describe this ticket in more detail.

**Comment by exa-eswar** [comment]
I am  trying to use Exasol's Pubilc Demo system to test this extension. 
I tested the BucketFS connection locally and it seems to be working fine, with HTTPS request, as I could upload the files into BucketFS.
While trying to upload the SLC of transformers-extension and corresponding UDFs, I got the following error. 


`requests.exceptions.ConnectionError: HTTPConnectionPool(host='demodb.exasol.com', port=2202): Max retries exceeded with url: /en_datascience/container/language_container.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7142299d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))`

The logs say the following:
`2022-10-04 14:16:32,392 - connectionpool  - Starting new HTTP connection (1): demodb.exasol.com:2202`

My initial suspicion was HTTP vs HTTPS, hence, I suggested this for a review. Please propose an alternate solution if this is not an issue.

**Comment by tkilias** [comment]
thx, for the clarification, I will have a look

**Comment by tkilias** [comment]
@exa-eswar did you try the command line parameter --bucketfs_use-https

**Comment by exa-eswar** [comment]
@tkilias yes, it is working, and I could see HTTPS passing through.
